[[bin]]
name = "learn_japanese"
path = "src/main.rs"

[[bin]]
name = "compile"
path = "src/compile.rs"

[package]
name = "learn_japanese"
version = "0.1.0"
edition = "2021"
default-run = "learn_japanese"

[dependencies]
term = "0.7.0"
crossterm_cursor = "0.4.0"
rand = "0.8.4"